name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install flake8 black
    - name: Lint with flake8
      run: |
        flake8 data_utils tests
    - name: Check formatting with black
      run: |
        black --check data_utils tests